CREATE TABLE users (
                       user_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                       uname VARCHAR(50) NOT NULL,
                       pwd_hash VARCHAR(255) NOT NULL,
                       role VARCHAR(10) NOT NULL,
                       created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                       CONSTRAINT pk_users
                           PRIMARY KEY (user_id),

                       CONSTRAINT uq_users_uname
                           UNIQUE (uname),

                       CONSTRAINT chk_users_role
                           CHECK (role IN ('admin', 'player'))
);


CREATE TABLE words (
                       word_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                       word VARCHAR(5) NOT NULL,

                       CONSTRAINT pk_words
                           PRIMARY KEY (word_id),

                       CONSTRAINT uq_words_word
                           UNIQUE (word),

                       CONSTRAINT chk_words_length
                           CHECK (LENGTH(word) = 5)
);


CREATE TABLE games (
                       game_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                       user_id BIGINT NOT NULL,
                       word_id BIGINT NOT NULL,
                       started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       completed_at TIMESTAMP,
                       status VARCHAR(20) NOT NULL DEFAULT 'IN_PROGRESS',

                       CONSTRAINT pk_games
                           PRIMARY KEY (game_id),

                       CONSTRAINT fk_games_user
                           FOREIGN KEY (user_id)
                               REFERENCES users(user_id),

                       CONSTRAINT fk_games_word
                           FOREIGN KEY (word_id)
                               REFERENCES words(word_id),

                       CONSTRAINT chk_games_status
                           CHECK (status IN ('IN_PROGRESS', 'WON', 'LOST'))
);


CREATE TABLE guesses (
                         guess_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                         game_id BIGINT NOT NULL,
                         guess_number INT NOT NULL,
                         guessed_word VARCHAR(5) NOT NULL,
                         result VARCHAR(5) NOT NULL,
                         created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                         CONSTRAINT pk_guesses
                             PRIMARY KEY (guess_id),

                         CONSTRAINT fk_guesses_game
                             FOREIGN KEY (game_id)
                                 REFERENCES games(game_id),

                         CONSTRAINT uq_guesses_game_number
                             UNIQUE (game_id, guess_number),

                         CONSTRAINT chk_guesses_number
                             CHECK (guess_number BETWEEN 1 AND 20),

                         CONSTRAINT chk_guesses_word_length
                             CHECK (LENGTH(guessed_word) = 5),

                         CONSTRAINT chk_guesses_result
                             CHECK (LENGTH(result) = 5)
);


CREATE TABLE IF NOT EXISTS game_config (
    config_id INT PRIMARY KEY DEFAULT 1,
    max_attempts INT NOT NULL DEFAULT 5,
    max_daily_games INT NOT NULL DEFAULT 3,
    game_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT chk_single_config CHECK (config_id = 1)
);

INSERT INTO game_config (config_id, max_attempts, max_daily_games, game_enabled)
VALUES (1, 5, 3, TRUE)
ON CONFLICT (config_id) DO NOTHING;